-- Generated from src/data/seed-data.json by scripts/generate-seed-sql.js
-- Do not edit by hand — edit seed-data.json and re-run: npm run seed:generate

delete from routes;
delete from landmarks;

-- Landmarks (15, Zone 1: Makerere / Wandegeya / Mulago / Town)
insert into landmarks (name, alias, lat, lng, photo_url, type) values
  ('Makerere Main Gate', '{"Makerere Gate","Main Gate","Makerere"}', 0.3335, 32.5676, 'https://picsum.photos/seed/makerere_main_gate/400/300', 'gate'),
  ('Makerere University Hospital', '{"University Hospital","Uni Hospital"}', 0.3278, 32.5708, 'https://picsum.photos/seed/university_hospital/400/300', 'hospital'),
  ('Ham Towers', '{"Ham Tower","Ham Building"}', 0.328, 32.5704, 'https://picsum.photos/seed/ham_towers/400/300', 'landmark'),
  ('Wandegeya Taxi Stage', '{"Wandegeya Stage","Taxi Stage"}', 0.33, 32.574, 'https://picsum.photos/seed/wandegeya_taxi_stage/400/300', 'stage'),
  ('Wandegeya Total', '{"Total Wandegeya","Total Makerere","Total Petrol Station"}', 0.3298, 32.573, 'https://picsum.photos/seed/wandegeya_total/400/300', 'fuel_station'),
  ('Wandegeya Market', '{"Wandegeya Mkt"}', 0.331, 32.5734, 'https://picsum.photos/seed/wandegeya_market/400/300', 'market'),
  ('Wandegeya Police Post', '{"Wandegeya Police","Wandegeya Police Station"}', 0.3297, 32.5745, 'https://picsum.photos/seed/wandegeya_police_post/400/300', 'landmark'),
  ('Bombo Road Junction', '{"Bombo Rd Junction"}', 0.3345, 32.5747, 'https://picsum.photos/seed/bombo_road_junction/400/300', 'junction'),
  ('CPS Roundabout', '{"Central Police Roundabout","CPS","Central Police Station"}', 0.3161, 32.5785, 'https://picsum.photos/seed/cps_roundabout/400/300', 'roundabout'),
  ('Old Taxi Park', '{"Taxi Park","Town"}', 0.3122, 32.577, 'https://picsum.photos/seed/old_taxi_park/400/300', 'landmark'),
  ('Mulago Roundabout', '{"Mulago R/A"}', 0.3383, 32.5753, 'https://picsum.photos/seed/mulago_roundabout/400/300', 'roundabout'),
  ('Mulago Hospital Main Gate', '{"Mulago Hospital","Mulago","Mulago National Referral Hospital"}', 0.3389, 32.5758, 'https://picsum.photos/seed/mulago_hospital_gate/400/300', 'hospital'),
  ('Kubiri', '{"Kubiri Mulago"}', 0.338, 32.5725, 'https://picsum.photos/seed/kubiri/400/300', 'junction'),
  ('Clock Tower', '{"Town Clock Tower"}', 0.3094, 32.5784, 'https://picsum.photos/seed/clock_tower/400/300', 'landmark'),
  ('Nakasero Market', '{"Nakasero Mkt"}', 0.3118, 32.5805, 'https://picsum.photos/seed/nakasero_market/400/300', 'market');

-- Routes (20, hardcoded for Zone 1 — 10 landmark pairs x 2 directions)
insert into routes (id, start_name, end_name, steps_json, boda_price_min, boda_price_max, panya_tip) values
  ('makerere_main_gate_to_wandegeya_total', 'Makerere Main Gate', 'Wandegeya Total', '[{"order":1,"text":"Start at Makerere Main Gate. Face out of campus and go downhill on the tarmac road.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"},{"order":2,"text":"Pass University Hospital on your right side. Keep going straight, don''t branch anywhere.","landmark":"Makerere University Hospital","lat":0.3278,"lng":32.5708,"photo_url":"https://picsum.photos/seed/university_hospital/400/300"},{"order":3,"text":"Ham Towers will be on your right, that''s where the boda guys wait. You''re almost there.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"},{"order":4,"text":"You have arrived at Total Wandegeya, the big fuel station on your left.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"}]'::jsonb, 3000, 5000, 'If traffic is jammed near Wandegeya roundabout, boda can use the small road behind Ham Towers to skip it.'),
  ('wandegeya_total_to_makerere_main_gate', 'Wandegeya Total', 'Makerere Main Gate', '[{"order":1,"text":"Start at Total Wandegeya, the fuel station facing Bombo Road. Head uphill towards Makerere.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"},{"order":2,"text":"Ham Towers passes on your left now, boda stage there. Keep straight, uphill.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"},{"order":3,"text":"University Hospital appears on your left. The gate is getting close.","landmark":"Makerere University Hospital","lat":0.3278,"lng":32.5708,"photo_url":"https://picsum.photos/seed/university_hospital/400/300"},{"order":4,"text":"You have arrived at Makerere Main Gate. Welcome to campus.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"}]'::jsonb, 3000, 5000, 'Coming from Wandegeya, if the road is jammed, branch near Ham Towers — it rejoins near the gate.'),
  ('makerere_main_gate_to_wandegeya_taxi_stage', 'Makerere Main Gate', 'Wandegeya Taxi Stage', '[{"order":1,"text":"Start at Makerere Main Gate, go down towards Wandegeya side.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"},{"order":2,"text":"Ham Towers will be on your right, boda guys wait there. Keep straight towards the taxi stage.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"},{"order":3,"text":"You have arrived at Wandegeya Taxi Stage, full of taxis and bodas.","landmark":"Wandegeya Taxi Stage","lat":0.33,"lng":32.574,"photo_url":"https://picsum.photos/seed/wandegeya_taxi_stage/400/300"}]'::jsonb, 2000, 3000, 'Boda guys cut behind Ham Towers to dodge the Wandegeya roundabout jam.'),
  ('wandegeya_taxi_stage_to_makerere_main_gate', 'Wandegeya Taxi Stage', 'Makerere Main Gate', '[{"order":1,"text":"Start at Wandegeya Taxi Stage, head towards Ham Towers side.","landmark":"Wandegeya Taxi Stage","lat":0.33,"lng":32.574,"photo_url":"https://picsum.photos/seed/wandegeya_taxi_stage/400/300"},{"order":2,"text":"Ham Towers passes on your left, boda stage there.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"},{"order":3,"text":"You have arrived at Makerere Main Gate.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"}]'::jsonb, 2000, 3000, 'Boda guys cut behind Ham Towers to dodge the Wandegeya roundabout jam.'),
  ('makerere_main_gate_to_mulago_hospital_gate', 'Makerere Main Gate', 'Mulago Hospital Main Gate', '[{"order":1,"text":"Start at Makerere Main Gate, head down to Wandegeya.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"},{"order":2,"text":"Pass Wandegeya Taxi Stage, stay on the main tarmac. Don''t stop for the taxi touts.","landmark":"Wandegeya Taxi Stage","lat":0.33,"lng":32.574,"photo_url":"https://picsum.photos/seed/wandegeya_taxi_stage/400/300"},{"order":3,"text":"At Bombo Road Junction, branch right towards Mulago, not straight to town.","landmark":"Bombo Road Junction","lat":0.3345,"lng":32.5747,"photo_url":"https://picsum.photos/seed/bombo_road_junction/400/300"},{"order":4,"text":"Mulago Roundabout, the hospital signs start showing now.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":5,"text":"You have arrived at Mulago Hospital Main Gate.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"}]'::jsonb, 4000, 6000, 'At Bombo Road Junction during jam hours, bodas cut through Kubiri to reach Mulago faster.'),
  ('mulago_hospital_gate_to_makerere_main_gate', 'Mulago Hospital Main Gate', 'Makerere Main Gate', '[{"order":1,"text":"Start at Mulago Hospital Main Gate, face away from the hospital, head to the roundabout.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"},{"order":2,"text":"At Mulago Roundabout, take the road signposted Wandegeya / Makerere.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":3,"text":"Pass Bombo Road Junction, keep straight towards Wandegeya. Don''t branch to town.","landmark":"Bombo Road Junction","lat":0.3345,"lng":32.5747,"photo_url":"https://picsum.photos/seed/bombo_road_junction/400/300"},{"order":4,"text":"Wandegeya Taxi Stage on your right, keep going uphill.","landmark":"Wandegeya Taxi Stage","lat":0.33,"lng":32.574,"photo_url":"https://picsum.photos/seed/wandegeya_taxi_stage/400/300"},{"order":5,"text":"You have arrived at Makerere Main Gate.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"}]'::jsonb, 4000, 6000, 'At Bombo Road Junction during jam hours, bodas cut through Kubiri to reach Wandegeya faster.'),
  ('makerere_main_gate_to_old_taxi_park', 'Makerere Main Gate', 'Old Taxi Park', '[{"order":1,"text":"Start at Makerere Main Gate, head down to Wandegeya.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"},{"order":2,"text":"Pass Total Wandegeya on your right, continue straight on Bombo Road.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"},{"order":3,"text":"CPS Roundabout, the police station is on your left. Keep straight towards town center.","landmark":"CPS Roundabout","lat":0.3161,"lng":32.5785,"photo_url":"https://picsum.photos/seed/cps_roundabout/400/300"},{"order":4,"text":"You have arrived at Old Taxi Park, the heart of town.","landmark":"Old Taxi Park","lat":0.3122,"lng":32.577,"photo_url":"https://picsum.photos/seed/old_taxi_park/400/300"}]'::jsonb, 5000, 8000, 'Avoid Bombo Road at 5-7pm, it''s always jammed. Boda can use the back road near CPS to save 15 minutes.'),
  ('old_taxi_park_to_makerere_main_gate', 'Old Taxi Park', 'Makerere Main Gate', '[{"order":1,"text":"Start at Old Taxi Park, head north on Bombo Road, away from the clock tower.","landmark":"Old Taxi Park","lat":0.3122,"lng":32.577,"photo_url":"https://picsum.photos/seed/old_taxi_park/400/300"},{"order":2,"text":"Pass CPS Roundabout, keep straight. Don''t branch to Kampala Road.","landmark":"CPS Roundabout","lat":0.3161,"lng":32.5785,"photo_url":"https://picsum.photos/seed/cps_roundabout/400/300"},{"order":3,"text":"Total Wandegeya appears on your left, you''re almost at Makerere.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"},{"order":4,"text":"You have arrived at Makerere Main Gate.","landmark":"Makerere Main Gate","lat":0.3335,"lng":32.5676,"photo_url":"https://picsum.photos/seed/makerere_main_gate/400/300"}]'::jsonb, 5000, 8000, 'Avoid Bombo Road at 5-7pm, it''s always jammed. Boda can use the back road near CPS to save 15 minutes.'),
  ('wandegeya_total_to_mulago_hospital_gate', 'Wandegeya Total', 'Mulago Hospital Main Gate', '[{"order":1,"text":"Start at Total Wandegeya, face Bombo Road towards the Mulago side.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"},{"order":2,"text":"Pass Wandegeya Police Post on your right.","landmark":"Wandegeya Police Post","lat":0.3297,"lng":32.5745,"photo_url":"https://picsum.photos/seed/wandegeya_police_post/400/300"},{"order":3,"text":"At Bombo Road Junction, branch right towards Mulago.","landmark":"Bombo Road Junction","lat":0.3345,"lng":32.5747,"photo_url":"https://picsum.photos/seed/bombo_road_junction/400/300"},{"order":4,"text":"Mulago Roundabout, you''re almost there.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":5,"text":"You have arrived at Mulago Hospital Main Gate.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"}]'::jsonb, 3000, 5000, 'Boda shortcut through Kubiri avoids the Bombo Road Junction jam during rush hour.'),
  ('mulago_hospital_gate_to_wandegeya_total', 'Mulago Hospital Main Gate', 'Wandegeya Total', '[{"order":1,"text":"Start at Mulago Hospital Main Gate, head to the roundabout.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"},{"order":2,"text":"At Mulago Roundabout, take the road signposted Wandegeya.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":3,"text":"Pass Bombo Road Junction, keep straight to Wandegeya.","landmark":"Bombo Road Junction","lat":0.3345,"lng":32.5747,"photo_url":"https://picsum.photos/seed/bombo_road_junction/400/300"},{"order":4,"text":"Wandegeya Police Post on your left.","landmark":"Wandegeya Police Post","lat":0.3297,"lng":32.5745,"photo_url":"https://picsum.photos/seed/wandegeya_police_post/400/300"},{"order":5,"text":"You have arrived at Total Wandegeya.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"}]'::jsonb, 3000, 5000, 'Boda shortcut through Kubiri avoids the Bombo Road Junction jam during rush hour.'),
  ('wandegeya_total_to_old_taxi_park', 'Wandegeya Total', 'Old Taxi Park', '[{"order":1,"text":"Start at Total Wandegeya, face Bombo Road towards town.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"},{"order":2,"text":"CPS Roundabout, keep straight towards town center.","landmark":"CPS Roundabout","lat":0.3161,"lng":32.5785,"photo_url":"https://picsum.photos/seed/cps_roundabout/400/300"},{"order":3,"text":"You have arrived at Old Taxi Park.","landmark":"Old Taxi Park","lat":0.3122,"lng":32.577,"photo_url":"https://picsum.photos/seed/old_taxi_park/400/300"}]'::jsonb, 3000, 5000, 'Boda riders use the lane behind CPS to skip the roundabout jam.'),
  ('old_taxi_park_to_wandegeya_total', 'Old Taxi Park', 'Wandegeya Total', '[{"order":1,"text":"Start at Old Taxi Park, head north towards Wandegeya.","landmark":"Old Taxi Park","lat":0.3122,"lng":32.577,"photo_url":"https://picsum.photos/seed/old_taxi_park/400/300"},{"order":2,"text":"Pass CPS Roundabout, keep straight.","landmark":"CPS Roundabout","lat":0.3161,"lng":32.5785,"photo_url":"https://picsum.photos/seed/cps_roundabout/400/300"},{"order":3,"text":"You have arrived at Total Wandegeya.","landmark":"Wandegeya Total","lat":0.3298,"lng":32.573,"photo_url":"https://picsum.photos/seed/wandegeya_total/400/300"}]'::jsonb, 3000, 5000, 'Boda riders use the lane behind CPS to skip the roundabout jam.'),
  ('wandegeya_market_to_mulago_hospital_gate', 'Wandegeya Market', 'Mulago Hospital Main Gate', '[{"order":1,"text":"Start at Wandegeya Market, head out towards the Kubiri road.","landmark":"Wandegeya Market","lat":0.331,"lng":32.5734,"photo_url":"https://picsum.photos/seed/wandegeya_market/400/300"},{"order":2,"text":"Pass Kubiri, keep straight. Don''t branch into the market lane.","landmark":"Kubiri","lat":0.338,"lng":32.5725,"photo_url":"https://picsum.photos/seed/kubiri/400/300"},{"order":3,"text":"Mulago Roundabout, almost there now.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":4,"text":"You have arrived at Mulago Hospital Main Gate.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"}]'::jsonb, 3000, 5000, 'The Kubiri back road is a good shortcut avoiding the main Bombo Road jam near Wandegeya.'),
  ('mulago_hospital_gate_to_wandegeya_market', 'Mulago Hospital Main Gate', 'Wandegeya Market', '[{"order":1,"text":"Start at Mulago Hospital Main Gate, head to the roundabout.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"},{"order":2,"text":"At Mulago Roundabout, branch towards Kubiri.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":3,"text":"Pass Kubiri, continue straight.","landmark":"Kubiri","lat":0.338,"lng":32.5725,"photo_url":"https://picsum.photos/seed/kubiri/400/300"},{"order":4,"text":"You have arrived at Wandegeya Market.","landmark":"Wandegeya Market","lat":0.331,"lng":32.5734,"photo_url":"https://picsum.photos/seed/wandegeya_market/400/300"}]'::jsonb, 3000, 5000, 'The Kubiri back road is a good shortcut avoiding the main Bombo Road jam near Wandegeya.'),
  ('wandegeya_taxi_stage_to_ham_towers', 'Wandegeya Taxi Stage', 'Ham Towers', '[{"order":1,"text":"Start at Wandegeya Taxi Stage, walk towards Ham Towers.","landmark":"Wandegeya Taxi Stage","lat":0.33,"lng":32.574,"photo_url":"https://picsum.photos/seed/wandegeya_taxi_stage/400/300"},{"order":2,"text":"You have arrived at Ham Towers, boda guys wait right here.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"}]'::jsonb, 1000, 2000, 'Short walk, no need for a boda unless you''re carrying heavy luggage.'),
  ('ham_towers_to_wandegeya_taxi_stage', 'Ham Towers', 'Wandegeya Taxi Stage', '[{"order":1,"text":"Start at Ham Towers, head towards Wandegeya.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"},{"order":2,"text":"You have arrived at Wandegeya Taxi Stage.","landmark":"Wandegeya Taxi Stage","lat":0.33,"lng":32.574,"photo_url":"https://picsum.photos/seed/wandegeya_taxi_stage/400/300"}]'::jsonb, 1000, 2000, 'Short walk, no need for a boda unless you''re carrying heavy luggage.'),
  ('mulago_hospital_gate_to_clock_tower', 'Mulago Hospital Main Gate', 'Clock Tower', '[{"order":1,"text":"Start at Mulago Hospital Main Gate, head to the roundabout.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"},{"order":2,"text":"At Mulago Roundabout, take the road towards CPS / town.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":3,"text":"Pass CPS Roundabout, keep straight towards town.","landmark":"CPS Roundabout","lat":0.3161,"lng":32.5785,"photo_url":"https://picsum.photos/seed/cps_roundabout/400/300"},{"order":4,"text":"Nakasero Market will be on your left, keep going.","landmark":"Nakasero Market","lat":0.3118,"lng":32.5805,"photo_url":"https://picsum.photos/seed/nakasero_market/400/300"},{"order":5,"text":"You have arrived at Clock Tower, town center.","landmark":"Clock Tower","lat":0.3094,"lng":32.5784,"photo_url":"https://picsum.photos/seed/clock_tower/400/300"}]'::jsonb, 5000, 7000, 'Avoid this route at 6pm, the Mulago-CPS road jams badly. Boda riders detour through Wandegeya back streets.'),
  ('clock_tower_to_mulago_hospital_gate', 'Clock Tower', 'Mulago Hospital Main Gate', '[{"order":1,"text":"Start at Clock Tower, head north away from town center.","landmark":"Clock Tower","lat":0.3094,"lng":32.5784,"photo_url":"https://picsum.photos/seed/clock_tower/400/300"},{"order":2,"text":"Nakasero Market on your right, keep straight.","landmark":"Nakasero Market","lat":0.3118,"lng":32.5805,"photo_url":"https://picsum.photos/seed/nakasero_market/400/300"},{"order":3,"text":"Pass CPS Roundabout, keep straight towards Mulago.","landmark":"CPS Roundabout","lat":0.3161,"lng":32.5785,"photo_url":"https://picsum.photos/seed/cps_roundabout/400/300"},{"order":4,"text":"At Mulago Roundabout, branch towards the hospital.","landmark":"Mulago Roundabout","lat":0.3383,"lng":32.5753,"photo_url":"https://picsum.photos/seed/mulago_roundabout/400/300"},{"order":5,"text":"You have arrived at Mulago Hospital Main Gate.","landmark":"Mulago Hospital Main Gate","lat":0.3389,"lng":32.5758,"photo_url":"https://picsum.photos/seed/mulago_hospital_gate/400/300"}]'::jsonb, 5000, 7000, 'Avoid this route at 6pm, the Mulago-CPS road jams badly. Boda riders detour through Wandegeya back streets.'),
  ('ham_towers_to_kubiri', 'Ham Towers', 'Kubiri', '[{"order":1,"text":"Start at Ham Towers, head towards Bombo Road Junction.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"},{"order":2,"text":"Pass Bombo Road Junction, branch towards Kubiri.","landmark":"Bombo Road Junction","lat":0.3345,"lng":32.5747,"photo_url":"https://picsum.photos/seed/bombo_road_junction/400/300"},{"order":3,"text":"You have arrived at Kubiri.","landmark":"Kubiri","lat":0.338,"lng":32.5725,"photo_url":"https://picsum.photos/seed/kubiri/400/300"}]'::jsonb, 2000, 3500, 'This cuts through quieter roads, faster than going via Mulago Roundabout during rush hour.'),
  ('kubiri_to_ham_towers', 'Kubiri', 'Ham Towers', '[{"order":1,"text":"Start at Kubiri, head towards Bombo Road Junction.","landmark":"Kubiri","lat":0.338,"lng":32.5725,"photo_url":"https://picsum.photos/seed/kubiri/400/300"},{"order":2,"text":"Pass Bombo Road Junction, branch towards Wandegeya.","landmark":"Bombo Road Junction","lat":0.3345,"lng":32.5747,"photo_url":"https://picsum.photos/seed/bombo_road_junction/400/300"},{"order":3,"text":"You have arrived at Ham Towers.","landmark":"Ham Towers","lat":0.328,"lng":32.5704,"photo_url":"https://picsum.photos/seed/ham_towers/400/300"}]'::jsonb, 2000, 3500, 'This cuts through quieter roads, faster than going via Mulago Roundabout during rush hour.');
